CREATE TABLE T_STUDENT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20),
  AGE INT,
  BIRTHDAY DATE,
  CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE T_TEACHER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20),
  AGE INT,
  BIRTHDAY DATE,
  CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE T_CLASS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20),
  AGE INT,
  BIRTHDAY DATE,
  CREATE_TIME DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8;